markdown: kramdown
include: ['projekty','kategorie']
url: ''
baseurl: null
title: Kamil Podsiadło
description: Grafika 3D i więcej
site-image: assets/images/meta.jpg
site-keywords: 'Kamil, Podsiadło, Portfolio, Grafika 3D'
favicon-url: >-
  https://img.myloview.pl/naklejki/icon-3d-3d-text-isometric-isolated-text-on-white-backogrund-400-242492760.jpg
heroimage: >-
  https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940
email: kamilpodsiadlo1234@gmail.com
facebook_username:
twitter_username:
instagram_username:
useme_username: kamil-podsiadlo,199388/
linkedin_username: kamil-podsiadło-a25a80200/
github_username:
youtube_channel_id:
reddit_username: 
behance_username: 
dribbble_username: 
spotify_username: 
google-analytics: UA-163806439-1
disqus-shortname: thedevslot
author-name: TheDevsLot
author-image: /assets/images/Kamil.jpg
author-about: >-
  Moim głównym zainteresowaniem jest grafika komputerowa- głównie 3D, którą
  zacząłem zajmować się już w wieku 14 lat. Lubię również programować, choć nie
  robię tego często. 
  Przykładowo owa strona jest zrobiona przeze mnie z wykorzystaniem technologii Jekyll oraz znajomości HTML, CSS, JavaScript.
  Przez ostatni rok pracowałem w temacie grafiki 3D m. in. jako projektant
  wnętrz ds. wizualizacji 3D.
author-url: /
sass:
  sass_dir: _sass
  style: compressed
plugins:
  - jekyll-admin
  - jekyll-feed
permalink: 'blog/:title'
compress_html:
  clippings: all
defaults:
  - scope:
      type: posts
    values:
      layout: post
      post-image: ''
      description: ''
      tags:
        - ''
  - scope:
      type: pages
    values:
      layout: page
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
